version: "3.7"
services:
  worker:
      container_name: worker-implementasi-pox
      build: ./containernet
      depends_on:
        - redis
      tty: true
      privileged: true
      network_mode: "host"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /lib/modules:/lib/modules

  web:
    restart: "always"
    container_name: flask-implementasi-pox
    build: ./web
    depends_on:
      - db
      - redis
    ports:
      - "3000:5000"

  redis:
    restart: "always"
    container_name: redis-implementasi-pox
    image: "redis:alpine"

  db:
    restart: "always"
    container_name: mysql-implementasi-pox
    image: mysql:5.7
    ports:
      - "3200:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  phpmyadmin:
    restart: "always"
    container_name: phpmyadmin-implementasi-pox
    image: phpmyadmin/phpmyadmin
    ports:
      - "9000:80"
    depends_on:
      - db
